### ISSUE TITLE
Online IDE compile error for Beacon

### ISSUE THREAD

**Issue by MaggieMei** [ARMmbed/mbed-os-example-ble#84] opened 2017-06-13 06:39 UTC
Error: Cannot open source input file "nrf.h": No such file or directory in "extras/BLE_Thermometer/mbed-os.lib/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/device/cmsis.h", Line: 21, Col: 18

**Comment by pan-** [comment] 2017-06-13 08:34
@MaggieMei That would help with a bit of context. From the path, it doesn't looks like you are compiling Beacon but rather the BLE_Thermometer example. 

Could you share with me a link to your project ?

**Comment by pan-** [comment] 2017-06-15 09:40
@MaggieMei Any update ?

**Comment by MarceloSalazar** [comment] 2017-09-23 15:01
Can't reproduce - closing.

**Closed by MarceloSalazar** 2017-09-23 15:01 UTC
