### ISSUE TITLE
[OOB_5_4_RC1] NUCLEO_F207ZG Pinmap not found

### ISSUE THREAD

**Issue by mbartling** [ARMmbed/mbed-os-example-ble#60] opened 2017-03-02 20:50 UTC
Hi all,

working on the 5.4 oob for mbed-os-example-ble/BLE_URIBeacon on the Nucleo f207zg board and I am getting "pinmap not found for peripheral" when I run the compiled code. 

![nucleof207zg](https://cloud.githubusercontent.com/assets/5848519/23526448/f1721da0-ff46-11e6-8f99-97e3e2e49868.PNG)

**Comment by ashok-rao** [comment] 2017-03-06 10:10
@mbartling  .. can you try the instructions under "Using ST Nucleo shield on other targets" section of the docs?
@pan- .. any other suggestions?

**Comment by pan-** [comment] 2017-03-06 14:10
@ashok-rao If `IDB0XA1_D13_PATCH` is defined in `mbed_app.json` as indicated in the instructions then it compiles just fine.

**Comment by mbartling** [comment] 2017-03-06 16:09
It compiles fine with or without the patch. I get the error during runtime

**Comment by mbartling** [comment] 2017-03-06 17:40
It compiles fine with the patch, but the Physical Web app always fails to find the beacon

**Comment by ashok-rao** [comment] 2017-03-06 18:08
@mbartling , yes. This is now a known issue. Have a look at this: [https://github.com/ARMmbed/mbed-os-example-ble/issues/62]()

@sg- @pan-

**Comment by mbartling** [comment] 2017-03-06 18:16
FYI: so far it doesnt look like a pin issue. I tried the swapping the resistors on the ble shield and following the instructions on this link https://developer.mbed.org/teams/ST/code/X_NUCLEO_IDB0XA1/ Still doesnt work

**Comment by pan-** [comment] 2017-03-06 18:57
@apalmieriGH what can be wrong with the NUCLEO_F207ZG ?

**Comment by apalmieriGH** [comment] 2017-03-07 09:02
@mbartling what is the BLE shield you are using? Can you try another example to check if the same issue occurs?

**Comment by pan-** [comment] 2017-03-07 09:50
@apalmieriGH I believe he's using the` IDB05A1`, I wonder if the pin mapping of the `NUCLEO_F207ZG` is well defined.

**Comment by apalmieriGH** [comment] 2017-03-07 13:07
@mbartling can you try the suggestion by @mray19027 reported here: https://github.com/ARMmbed/mbed-os/issues/3541 ?

@pan-

**Comment by MarceloSalazar** [comment] 2017-03-10 12:34
@mbartling could you please provide an update on this?

**Comment by mbartling** [comment] 2017-03-10 16:14
Hey @MarceloSalazar, worked with @mray19027 he is having issues compiling and I am still having the pinmap not found when I run the code.

**Comment by MarceloSalazar** [comment] 2017-04-05 11:25
> Also tried to update the repository and now it no longer exists as of 5.4

Correct, BLE_URIBeacon example has been deprecated - we should use an alternative example (feel free to close this ticket an open a new one).

> he is having issues compiling and I am still having the pinmap not found when I run the code.

If this is not working in 5.4.x, could you share more information? (build logs, serial output, environment info, etc).

**Comment by pan-** [comment] 2017-04-05 13:15
@MarceloSalazar Others reported the issue [here](https://github.com/ARMmbed/mbed-os-example-ble/issues/40#issuecomment-291452560). The issue is impacting NUCLEO_F4xx based targets when they used mbed OS 5.4, the combination K64F + BLE shield is fine though.

**Closed** 2017-06-13 08:36 UTC
