### ISSUE TITLE
Does not compile with nRF52-DK

### ISSUE THREAD

**Issue by Navis-Raven** [ARMmbed/mbed-os-example-ble#169] opened 2018-08-10 22:07 UTC
When selecting BLE_Button for nRF52-DK, the programm does not compile, and the hardware included is not the good one (ours is nRF52832 and not nRF51822)

![image](https://user-images.githubusercontent.com/15887222/43983266-ff67c64c-9cf9-11e8-92c4-d7e4c9ce9325.png)

**Comment by ciarmcom** [comment] 2018-08-10 23:50
ARM Internal Ref: MBOTRIAGE-1513

**Comment by pan-** [comment] 2018-08-13 16:02
Are you using https://os.mbed.com/teams/mbed-os-examples/code/mbed-os-example-ble-Button/ ? 
That is the version we maintain and that is synced with this repository.

**Comment by Navis-Raven** [comment] 2018-08-13 16:06
Select the nRF52-DK as a hardware one Mbed compiler, then new, at just after the BLE_BUTTON is selected automatically, and this is the software which has a problem. Maybe this is not the version you maintain, I don't know

**Comment by pan-** [comment] 2018-08-13 16:43
I've just tried the version I linked; it compiles without trouble. Please try it; that is the only version we maintain.

**Comment by Navis-Raven** [comment] 2018-08-13 17:17
So this is not the problematic version.

**Comment by Navis-Raven** [comment] 2018-08-13 17:18
If the other version is not maintained, so you have to remove it from the default example list and replace it by this one.

**Comment by ConradBraam** [comment] 2019-02-14 16:54
![two-projects](https://user-images.githubusercontent.com/41382020/52801487-ddae3800-3075-11e9-9ee0-1ea07af91996.PNG)
Hi Navis-Raven , I managed to reproduce. I see that the "new project" wizard is importing a project with the same name which is MBED Version 2. You do not see the same projects available here, because the wizard is picking up ones the vendor/target originally added at the time.
We want to use mbed 5.X  for new designs, else you will not be getting support for any new features and getting much assistance I imagine. The browser list probably should show you V5 projects in that list, but mbed don't control that list, so the way to go is to **import the program from the mbed examples, then choose your target**. This gets you the new example.

I hope these steps help the next person.
1. go to the new project https://os.mbed.com/teams/mbed-os-examples/code/mbed-os-example-ble-Button/ , and tap the "import into compiler" button
2. Choose a unique program name, then change your target to the one you really want. I choose the STD52832B as a challenge. 
3. The compile fails, because this target does not have a button built in, so you will have to wire one in, I chose to use GPIO0 (which is an LED actually but just using it so it will compile)
 So I edit the mbed_app.json file, and add these lines to support the target
"SDT52832B": {
            "target.features_add": ["BLE"],
            "target.extra_labels_add": ["CORDIO", "CORDIO_LL", "SOFTDEVICE_NONE", "NORDIC_CORDIO"],
            "target.extra_labels_remove": ["SOFTDEVICE_COMMON", "SOFTDEVICE_S132_FULL", "NORDIC_SOFTDEVICE"],
            "ble_button_pin_name": "GPIO0"
        },
4. Hit compile again.
If these steps do work for you, let me know, so I can "attempt" to fix the flow for future users.

Note: I have not verified that the SDT52832B actually works, just laying the steps logically I hope.

**Comment by Navis-Raven** [comment] 2019-02-15 10:34
@ConradBraam hi, thanks for your answer, but I cannot make a test anymore since à I returned back the nRF52-DK board to it's owner since September 2018. 

However, what I point here is that it has to work from the beginning without anymore else configuration. So the Arm Mbed Compiler has te edit json file and all configuration files in order to generate the Keil project without any additionnal configuration.

**Comment by ConradBraam** [comment] 2019-02-15 11:10
No problem about the NRF52. Your main issue was compile-fail, for compiling code no longer in support. So I have asked web team to fill the examples list with all the new mbed5 examples instead :-) (Should happen early next week.) That should prevent the original issue - but not your JSON and Keil export issue.

I think we need to remember that the JSON editing is a larger problem because it requires keeping the "app level" configuration data for over a dozen examples all in sync, so that's why we limit the amount of targets we explicitly support, it's often easy enough to copy-paste once you know what you are doing. Which is why I explained the json file editing in a bit of detail above. We have over 100 targets supported. Targets are themselves just templates for dev boards, which get ignored when moving to production anyway, so of less value to anything in a real application. If there are ways we can simplify the JSON editing process with better documentation, do let me know, docs are easy to change.

My only advice on getting projects exported into Keil to run offline is to start over from scratch and have a lot of Keil experience already. I have had projects export but require minor perfectly simple settings changes on older builds. But the examples are just that, a starting place to learn from, a known good reference point, and that you need to be prepared to throw away and fully design an app instead. The examples are often not scaleable. So fresh start is best, but yes, the examples must actually work 100%!

I kind of get that you are raising this as a way of getting mbed to make things easier, I hope that removing the old examples and putting the many more new ones into the examples list for NRF52 will now solve some of that. Users also want to look out for a new mbed Studio coming soon. https://os.mbed.com/docs/mbed-os/v5.11/tools/developing-mbed-studio.html It will support online and offline (win/gnu-linux/mac) using arm compiler I believe.

**Comment by Navis-Raven** [comment] 2019-02-15 15:48
@ConradBraam  if facts I've since then, I've uninstalled Keil and abandonned this editor, and I switched to VSCode with PlatformIO plugin, it install and configure all you want with code example for more than... 500 boards (not only ARM based).

The good thing is tha PlatformIO is open source, I don't know but maybe you can find your answer of how generating some config file for these boards... 

"My only advice on getting projects exported into Keil to run offline is to start over from scratch and have a lot of Keil experience already."
That's the whole problem... The main problem of beginning a new project is configuration. And if you don't have "this lot of Keil experience already" you're dead. Note that I had a similar problem with IAR and arm online compiler which was not up to date. 

The online arm compiler should have to simplify the configuration by offering this possibility of exporting with "zero configuration" (or near zero configuration)

"want to look out for a new mbed Studio coming soon." At last, a true arm mbed studio.... I'see that is based on eclipse. Unfortunately the arm tools have many bugs (not only this one), and I had many problems with them, and the developpement and bug correction is very slow . As I said before, I prefered tos switch to VSCode with platformIO there is less bugs and zero configuration (except the driver installation). 
https://platformio.org
https://code.visualstudio.com

**Comment by ConradBraam** [comment] 2019-02-18 09:47
Just want to correct something, the new mbed studio in alpha currently is not Eclipse based, it's java, but one of the new frameworks which allow running in browser and offline all in one familiar app. It should also be making OpenOCD debug setup painless. About 10 years ago I worked with a bloke who only coded in a plain text editor, he had systemized and memorized all the names he needed to and intelli-sense was not necessary, it was in his head. He only used the IDE for debugging. It's a very context sensitive art, and my fave right now it CLion, I'll be buying a license soon. 

Once I have solved the problem with old examples being presented to users, I will close this ticket off. There are a whole load of new examples that will appear in that list shortly. Thanks for highlighting this. Since that was the original issue, one issue per ticket.

**Comment by Navis-Raven** [comment] 2019-02-18 13:00
"is not Eclipse based, it's java"
Eclipse is itself based on Java.

But  it seems that you're right, since there is some updates
![image](https://user-images.githubusercontent.com/15887222/52952623-69310d00-3385-11e9-9e9d-23b559b154c1.png)

**Comment by Navis-Raven** [comment] 2019-02-18 13:04
I don't know about CLion but now I've found a very good IDE with very good plugin which facilitates all thinggs, and it is PlatformIO

**Comment by Navis-Raven** [comment] 2019-02-18 13:08
There is an arm mbed extension for vscode but I think not as good as PlatformIO

![image](https://user-images.githubusercontent.com/15887222/52953025-97631c80-3386-11e9-817b-de9bd957e70c.png)

**Comment by ciarmcom** [comment] 2019-10-31 21:20
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by Navis-Raven** [comment] 2019-10-31 21:22
@ConradBraam what's new about this bug ?

**Comment by adbridge** [comment] 2019-11-01 15:55
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by ciarmcom** [comment] 2019-11-13 16:41
*Internal Jira reference: https://jira.arm.com/browse/IOTPAN-529*

**Comment by ciarmcom** [comment] 2020-10-01 14:47
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-2058*

**Comment by pan-** [comment] 2020-10-02 08:10
I'm closing this. It is unrelated to the examples in this repository.

**Closed by pan-** 2020-10-02 08:10 UTC
Labels: IOTOSM-2058, Jira status: OPEN, mirrored, type: bug

**Comment by Navis-Raven** [comment] 2020-10-02 14:36
> I'm closing this. It is unrelated to the examples in this repository.

That's false. Off course it was related to the examples in the repository (see below)
![image](https://user-images.githubusercontent.com/15887222/94934978-b61b1600-04cc-11eb-8636-ebb4183d7141.png)

I don't know how your project evolved since 2018, if after two years I declared this bug, it's the only answer you give... it is quite revolting for the users.
